### ISSUE TITLE
ACAB Sticker sind nicht color-proof

### ISSUE THREAD

**Issue by codec** [muccc/Aufkleber#1]
Die letzte Ladung ACAB Sticker ist leider fabrlich völlig verfälscht. @andz82 Kannst Du 'ne Aussage dazu machen ob das Source Material oder der Druck vermurkst wurde?

**Comment by andz82** [comment]
Die Druckdaten für die ACAB-Aufkleber waren im (für Flyeralarm) falschen Farbraum. --> blau wurde lila...Sollte vor der nächsten Bestellung gefixt werden.

Aber...ALL colours are beautiful...auch lila ;)
